apiVersion: v1
kind: Service
metadata:
  name: app-three-service
spec:
  type: ClusterIP
  selector:
    # App in the deployment which the service will serve
    app: app-three
  ports:
    - name: http
      port: 80 # service port
      targetPort: 8080 # container port
